import type { ConciergeRequestType } from './concierge';
import type { StaffRole } from './staff';

export type IntentCategory = 'business' | 'celebration' | 'health_wellness' | 'leisure' | 'life_travel';

/** A selectable travel-purpose template. Only `deepBuilt` templates generate a real, fully authored Experience Blueprint — others show breadth without pretending a checklist exists yet. */
export interface IntentTemplate {
  id: string;
  label: string;
  category: IntentCategory;
  description: string;
  deepBuilt: boolean;
}

/** One intent attached to a booking. `weightPercent` is informational (shown to the guest), not enforced arithmetic. */
export interface BookingIntent {
  templateId: string;
  role: 'primary' | 'secondary';
  weightPercent: number;
}

export type BlueprintItemKind = 'auto_ready' | 'concierge_request' | 'intent_task';

/** One line of a guest's Experience Blueprint / "Today's Mission" checklist. */
export interface BlueprintItem {
  id: string;
  label: string;
  kind: BlueprintItemKind;
  /** Present when kind === 'concierge_request' — status is read from the matching ConciergeRequest. */
  conciergeRequestType?: ConciergeRequestType;
  /** Present when kind === 'intent_task' — status is read from the matching IntentTask. */
  department?: StaffRole;
  done: boolean;
}

/**
 * A hotel-side task generated by a blueprint item that has no existing ConciergeRequestType
 * to route through (e.g. "confirm a quiet room"). Mirrors ConciergeRequest's shape rather
 * than introducing a generic Task/Notification abstraction.
 */
export interface IntentTask {
  id: string;
  bookingId: string;
  guestId: string;
  hotelId: string;
  templateId: string;
  label: string;
  department: StaffRole;
  status: 'pending' | 'done';
  createdAt: string;
  completedAt: string | null;
}

/** One item of a booking-time feasibility check — decided once, from real availability/amenity data, never from staff activity during the stay. */
export interface MatchAssessmentItem {
  id: string;
  label: string;
  matched: boolean;
  /** Present when matched is false — a factual, non-alarming explanation (e.g. "Limited availability for these dates"). */
  note?: string;
}

/**
 * The honest, immediate answer to "how well can we match this guest's stated Intent",
 * computed once at booking time from real inventory/amenity data and stored on the
 * Booking — never recomputed later, so it can't drift as unrelated bookings change live
 * availability, and never fed by whether hotel staff got around to completing a task.
 */
export interface IntentMatchAssessment {
  templateId: string;
  items: MatchAssessmentItem[];
  matchedCount: number;
  totalCount: number;
  scorePercent: number;
}
